### PR TITLE
Replace crafting table GUI w/ the fast one

### PR DESCRIPTION
**Pull request by T145**
🌴

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
wat

**Comment by T145** [comment]
Have you looked at the code? This would allow you to not have to register your own crafting table or GUI handler. The mod also becomes automatically compatible w/ *any* other mod that opens a plain `GuiCrafting`.

**Comment by Shadows-of-Fire** [comment]
I havw.  It would not.  It would invalidate the mod by trying to make it client only.

**Comment by T145** [comment]
So just so to understand, the way I have things set up means you get the GUI benefits but not the Container benefits?

**Comment by Shadows-of-Fire** [comment]
Yeah

**Pull request closed without merging**
